apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec: #pod specification
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: #container specification
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 8080
